version: "3.8"

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=order_prj.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    volumes:
      - ./order_prj:/app
    networks:
      - order-network

networks:
  order-network:
    driver: bridge
