# Generated by Django 5.1.6 on 2025-03-05 04:55

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the customer', max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'blank': 'Email address is required.', 'null': 'Email address cannot be null.', 'unique': 'A customer with this email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('name', models.CharField(error_messages={'blank': 'Customer name is required.', 'max_length': 'Name cannot exceed 100 characters.'}, help_text='Customer full name', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number in international format', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', help_text='Current status of the customer account', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the customer was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the customer was last updated')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['email'], name='customer_email_idx'), models.Index(fields=['name'], name='customer_name_idx'), models.Index(fields=['status'], name='customer_status_idx'), models.Index(fields=['created_at'], name='customer_created_idx')],
            },
        ),
    ]
