# Generated by Django 5.1.6 on 2025-03-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, help_text="Date of customer's last order", null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(default=0, help_text='Total number of orders placed by customer'),
        ),
    ]
