# Generated by Django 5.1.6 on 2025-03-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_product_products_name_6f9890_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='PRODUCTS',
        ),
    ]
