version: "3.8"

services:
  product-service:
    build: .
    container_name: ecommerce-product-service
    ports:
      - "8002:8002"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=product_prj.settings
      - DJANGO_ALLOWED_HOSTS=*
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce_network
    external: true
