version: "3.8"

services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=product_prj.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    volumes:
      - ./product_prj:/app
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
