version: "3.8"

services:
  customer-service:
    build: ./customer-service
    ports:
      - "8001:8001"
    environment:
      - SNOWFLAKE_NAME=${SNOWFLAKE_NAME}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
    volumes:
      - ./customer-service:/app

  product-service:
    build: ./product-service
    ports:
      - "8002:8002"
    environment:
      - SNOWFLAKE_NAME=${SNOWFLAKE_NAME}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
    volumes:
      - ./product-service:/app

  order-service:
    build: ./order-service
    ports:
      - "8003:8003"
    environment:
      - SNOWFLAKE_NAME=${SNOWFLAKE_NAME}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
    volumes:
      - ./order-service:/app

networks:
  default:
    name: microservices-network
    driver: bridge
