# Generated by Django 5.1.7 on 2025-03-07 16:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order', max_length=36, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(help_text='Reference to Customer from Customer Service', max_length=36)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price of the order', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated')),
            ],
            options={
                'db_table': 'ORDERS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='order_customer_idx'), models.Index(fields=['status'], name='order_status_idx'), models.Index(fields=['created_at'], name='order_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=36)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order')),
            ],
            options={
                'db_table': 'ORDER_ITEMS',
                'indexes': [models.Index(fields=['order'], name='ORDER_ITEMS_order_i_9c5d0e_idx'), models.Index(fields=['product_id'], name='ORDER_ITEMS_product_56cd40_idx')],
            },
        ),
    ]
