# Generated by Django 5.1.7 on 2025-03-06 18:55

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order', max_length=36, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(help_text='Reference to Customer from Customer Service', max_length=36)),
                ('product_id', models.CharField(help_text='Reference to Product from Product Service', max_length=36)),
                ('quantity', models.PositiveIntegerField(help_text='Number of items ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the order', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the order', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the order was last updated')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='order_customer_idx'), models.Index(fields=['product_id'], name='order_product_idx'), models.Index(fields=['status'], name='order_status_idx'), models.Index(fields=['created_at'], name='order_created_idx')],
            },
        ),
    ]
