# Generated by Django 5.1.6 on 2025-03-05 09:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the order', max_length=36, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, help_text='Reference to customer in Customer service', max_length=36)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='orders_custome_6c3a7f_idx'), models.Index(fields=['status'], name='orders_status_762191_idx'), models.Index(fields=['created_at'], name='orders_created_77e2b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, help_text='Reference to product in Product service', max_length=36)),
                ('quantity', models.IntegerField(help_text='Quantity of product ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of product at time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, help_text='Total price for this line item', max_digits=10)),
                ('order', models.ForeignKey(help_text='Reference to parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order_app.order')),
            ],
            options={
                'db_table': 'order_items',
                'indexes': [models.Index(fields=['product_id'], name='order_items_product_a53db1_idx')],
            },
        ),
    ]
