# Generated by Django 5.1.6 on 2025-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(default='system', help_text='Username of the user who created the order', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(default='system', help_text='Username of the user who last updated the order', max_length=150),
        ),
    ]
