# Generated by Django 5.1.7 on 2025-03-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_order_total_price_alter_orderitem_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_product_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered')], default='pending', help_text='Current status of the order', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='ORDER_ITEMS_order_i_9c5d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_id'], name='ORDER_ITEMS_product_56cd40_idx'),
        ),
    ]
