# Generated by Django 5.1.7 on 2025-03-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_remove_order_order_product_idx_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
